Scheduler:
  CronPattern: '00 */30 * * * *'

Defaults:
  AWS:
    Proxy: http://proxy-ip:8888
    Support:
      Region: us-east-1
      Language: en
    Dynamo:
      Table: consigliere
      Region: ap-southeast-2
